---
- name: Deploy imap gateway
  hosts: gateway
  gather_facts: false

  tasks:
    - import_tasks: roles/gateway/tasks/context.yml
      tags:
        - context

    - import_tasks: roles/gateway/tasks/bootstrap.yml
      tags:
        - bootstrap

    - import_tasks: roles/gateway/tasks/clean.yml
      tags:
        - clean

    - import_tasks: roles/gateway/tasks/init.yml
      tags:
        - init

    - import_tasks: roles/gateway/tasks/download.yml
      tags:
        - download

    - import_tasks: roles/gateway/tasks/venv.yml
      tags:
        - venv

    - import_tasks: roles/gateway/tasks/install.yml
      tags:
        - install

    - import_tasks: roles/gateway/tasks/service.yml
      tags:
        - service

    - import_tasks: roles/gateway/tasks/healthcheck.yml
      tags:
        - healthcheck