---
- name: Gateway Deployment
  hosts: gateway
  gather_facts: false

  tasks:

    # ========================================================
    # Context
    # ========================================================
    - name: Context
      import_tasks: roles/app/tasks/context.yml
      tags:
        - context

    # ========================================================
    # Configuration
    # ========================================================
    - name: Configuration
      import_tasks: roles/app/tasks/configuration.yml
      tags:
        - configuration

    # ========================================================
    # Bootstrap
    # ========================================================
    - name: Bootstrap
      import_tasks: roles/app/tasks/bootstrap.yml
      tags:
        - bootstrap

    # ========================================================
    # Init
    # ========================================================
    - name: Init
      import_tasks: roles/app/tasks/init.yml
      tags:
        - init

    # ========================================================
    # Download
    # ========================================================
    - name: Download
      import_tasks: roles/app/tasks/download.yml
      tags:
        - download

    # ========================================================
    # Backup
    # ========================================================
    - name: Backup
      import_tasks: roles/app/tasks/backup.yml
      tags:
        - backup

    # ========================================================
    # Clean
    # ========================================================
    - name: Clean
      import_tasks: roles/app/tasks/clean.yml
      tags:
        - clean

    # ========================================================
    # Extract
    # ========================================================
    - name: Extract
      import_tasks: roles/app/tasks/extract.yml
      tags:
        - extract

    # ========================================================
    # Virtual Environment
    # ========================================================
    - name: Venv
      import_tasks: roles/app/tasks/venv.yml
      tags:
        - venv

    # ========================================================
    # Install
    # ========================================================
    - name: Install
      import_tasks: roles/app/tasks/install.yml
      tags:
        - install

    # ========================================================
    # Service
    # ========================================================
    - name: Service
      import_tasks: roles/app/tasks/service.yml
      tags:
        - service