---
- name: Deploy gateway application
  hosts: windows
  gather_facts: false

  tasks:
    - name: Validate deployment context
      import_tasks: roles/apps/tasks/context.yml
      tags: ['context']

    - name: Create deployment directories
      import_tasks: roles/apps/tasks/bootstrap.yml
      tags: ['bootstrap']